# Generated by Django 5.0.1 on 2024-01-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0008_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
